### ISSUE TITLE
Error: Cannot find module "dll-reference vendor_22bb1836*****"

### ISSUE THREAD

**Issue by 447491480** [likun7981/react-app-rewire-dll#1]
this rewire throw an error when hot replace。
![image](https://user-images.githubusercontent.com/8955429/37097164-b4c347ca-2255-11e8-98ab-dc7455d81d7a.png)

**Comment by alexesDev** [comment]
+1

**Comment by likun7981** [comment]
I'm very sorry for replying so late，you can see https://github.com/webpack/webpack/issues/5478

**Comment by alexesDev** [comment]
@likun7981 I found a solution before view this answer, but thans for quickly answer!
```js
config.cache = false;
return config;
```

**Comment by likun7981** [comment]
😄
